### PR TITLE
feat: bugsnag config (front and back)

### PR DESCRIPTION
**Pull request by brunobuddy**
## What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

feature

## Description

It adds support for Bugsnag for the client and the server.

## Related Issues

None.

## How Has This Been Tested?

To test this feature, please go [bugsnag](https://app.bugsnag.com/) and create a new project (type: "browser" and then "other"). This bugsnag project will server for logging from the client app AND the server app.

Get the API key from Bugsnag and then:

### In the client
- add the api key to `environment.ts`
- in `environment.ts` set _enableBugsnag_ to `true`

Then create a dummy error in the client in `app.component.ts`:
```js
  ngOnInit(): void {
     // This will fail.
     const wrong: any = {}
     console.log(wrong.wrong.wrongClient)
     [...]
}
```

### In the server
- make sure that your `.env` file is up to date and has the same properties as `.env.example` (values may change)
- in `.env` add your api key to BUGSNAG_API_KEY
- in `.env` set ENABLE_BUGSNAG=true

Then create a dummy error in the client in `user.controller.ts` in the `index()` function:
```js
  ): Promise<Paginator<User> | User[] | string> {
    const wrong: any = {}
    console.log(wrong.wrong.wrongServer)

    return await this.userService.index({
}
```
_EDIT_ : Then go to the "user list" to trigger the error

### What should I see then ?

- For the client error, you should have an error in Bugsnag giving you the name of the function (as it is on local, bugsnag does not have access to sourcemaps and cannot give you a better issues)
- For the server error you should have an error in Bugsnag that shows the file and number of the line.

### CODE REVIEW

**Comment by SebConejo** [comment]
@brunobuddy It seems to me that following all this process doesn't send any error to bugsnag.
- When the front error should be sent ? Directly after saving the file or should I go to a page on the front-end? 
- Are we agree that we excpect to receibe an error on the bugsnag dashboard ?

**Review by SebConejo — COMMENTED** [review]
@brunobuddy It seems to me that following all this process doesn't send any error to bugsnag.

When the front error should be sent ? Directly after saving the file or should I go to a page on the front-end?
Are we agree that we excpect to receibe an error on the bugsnag dashboard ?

**Comment by SebConejo** [comment]
@brunobuddy 
It looks ok now for me. Here is the result:

- On the front-end, I can see an error but without the sourcemaps (as you said, no sourcemaps on local environment)
- On the server side, I can see an error saying that something is undefined on user.controllerts, line 50

**Review by ismaelguerrib — APPROVED** [review]

**Comment by brunobuddy** [comment]
@SebConejo [documentation done](https://github.com/case-app/docs/commit/710a6cc6c40b958596e5d9080834e4236c8e8937), you can merge the PR if the doc is OK for you as @ismaelguerrib approved the PR.

**Pull request merged**
